name: Update Outdated Packages Badge

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-badge:
    runs-on: ubuntu-latest
    services:
      arch:
        image: archlinux:latest
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Environment
        run: |
          docker run --name arch-container -d archlinux:latest tail -f /dev/null
          docker exec arch-container pacman -Sy --noconfirm --needed pyalpm github-cli
          docker cp . arch-container:/src
      
      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: 'b5759b3d8a067b7e96f73934f43bf2ce'
        run: |
          OUTDATED=$(docker exec arch-container /usr/bin/sh -c 'cd /src/ && python -c "import compare; print(len(compare.lists()))"')
          echo "Outdated packages: $OUTDATED"
          if [ $OUTDATED -eq 1 ]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi
          gh api --method PATCH -H "Accept: application/vnd.github+json" \
            /gists/$GIST_ID \
            -f files[outdated-packages-multilib.json][content]="{
            \"schemaVersion\": 1,
            \"label\": \"Outdated Packages\",
            \"message\": \"$OUTDATED\",
            \"color\": \"$COLOR\"
            }"
